[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/404.html"
status = 404