[[redirects]]
from = "/about"
to = "/app/about"
status = 301

[[redirects]]
from = "/cv"
to = "/app/resume"
status = 200

[[redirects]]
from = "/twitch"
to = "/app/twitch"
status = 200

[[redirects]]
from = "/recommendations"
to = "/app/recommendations"
status = 200

[[redirects]]
from = "/contact"
to = "/app/contact"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/404.html"
status = 404